blank_issues_enabled: false

contact_links:
  - name: General Discussion
    url: https://github.com/Jeepmeta/mgp-spec/discussions
    about: Use discussions for questions, brainstorming, or non-issue conversations.
